---
- name: Remove obsolete Certbot PPA key
  apt_key:
    id: "{{ nginx_certbot_ubuntu_apt_key }}"
    # https://unix.stackexchange.com/a/110594
    keyserver: "hkps://keyserver.ubuntu.com:443"
    state: absent
  become: true
  become_user: root

- name: Remove obsolete Certbot PPA
  apt_repository:
    repo: >-
      deb
      http://ppa.launchpad.net/certbot/certbot/ubuntu
      {{ ansible_distribution_release }}
      main
    update_cache: true
    state: absent
  become: true
  become_user: root

- name: Remove obsolete Certbot packages
  apt:
    name:
      # This is Python 3, but named differently in the PPA
      - python-certbot-nginx
      - python3-certbot-nginx
      - certbot
      - python3-certbot
    force_apt_get: true
    state: absent
  become: true
  become_user: root
