---
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: ubuntu18
    image: solita/ubuntu-systemd:18.04
    privileged: false
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
    security_opts:
      - seccomp=unconfined
    networks:
      - name: molecule
    groups:
      - targets
  - name: pebble
    # Until Certbot >= 0.34.0 is used, Pebble needs an older version
    # https://github.com/letsencrypt/pebble/issues/192
    image: letsencrypt/pebble:v1.0.1
    pre_build_image: true
    override_command: false
    env:
      PEBBLE_VA_NOSLEEP: "1"
      PEBBLE_VA_ALWAYS_VALID: "1"
    networks:
      - name: molecule
    groups:
      - services
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
verifier:
  name: testinfra
  options:
    hosts: targets
