---
lint:
  name: yamllint
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: ubuntu18
    image: solita/ubuntu-systemd:18.04
    privileged: false
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
    security_opts:
      - seccomp=unconfined
    networks:
      - name: molecule
    groups:
      - targets
  - name: pebble
    # Until Certbot >= 0.34.0 is used, Pebble needs an older version
    # https://github.com/letsencrypt/pebble/issues/192
    image: letsencrypt/pebble:v1.0.1
    pre_build_image: true
    override_command: false
    env:
      PEBBLE_VA_NOSLEEP: "1"
      PEBBLE_VA_ALWAYS_VALID: "1"
    networks:
      - name: molecule
    groups:
      - services
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      targets:
        # Defining this here, instead of in playbooks, also ensures it's picked
        # up by Testinfra
        ansible_python_interpreter: "/usr/bin/python3"
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
scenario:
  name: default
verifier:
  name: testinfra
  options:
    hosts: targets
    W: ignore::DeprecationWarning
  lint:
    name: flake8
