---
lint: |
  set -e
  yamllint --config-data '{extends: relaxed, ignore: .tox/}' .
  ansible-lint --exclude '.tox/'
  flake8
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: ubuntu18
    image: jrei/systemd-ubuntu:18.04
    privileged: false
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    networks:
      - name: molecule
    network_mode: default
    groups:
      - targets
  - name: ubuntu20
    image: jrei/systemd-ubuntu:20.04
    privileged: false
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    networks:
      - name: molecule
    network_mode: default
    groups:
      - targets
  - name: pebble
    # Until Certbot >= 0.34.0 is used, Pebble needs an older version
    # https://github.com/letsencrypt/pebble/issues/192
    image: letsencrypt/pebble:latest
    pre_build_image: true
    override_command: false
    env:
      PEBBLE_VA_NOSLEEP: "1"
      PEBBLE_VA_ALWAYS_VALID: "1"
    networks:
      - name: molecule
    network_mode: default
    groups:
      - services
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
verifier:
  name: testinfra
  options:
    hosts: targets
