---
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: ubuntu18
    image: ubuntu:18.04
    dockerfile: Dockerfile.j2
    override_command: false
    # Docker options for https://github.com/ogra1/snapd-docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    devices:
      - /dev/fuse
    capabilities:
      - SYS_ADMIN
    security_opts:
      - apparmor=unconfined
      - seccomp=unconfined
    networks:
      - name: molecule
    groups:
      - targets
  - name: pebble
    image: letsencrypt/pebble:latest
    pre_build_image: true
    override_command: false
    env:
      PEBBLE_VA_NOSLEEP: "1"
      PEBBLE_VA_ALWAYS_VALID: "1"
    networks:
      - name: molecule
    groups:
      - services
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
verifier:
  name: testinfra
  options:
    hosts: targets
