---
- name: Prepare
  hosts: targets
  tasks:
    - name: Install snap core runtime
      snap:
        name: core
        channel: edge
      become: true
      become_user: root
    - name: Preconfigure Certbot to use local service for ACME
      ini_file:
        path: "{{ ansible_user_dir }}/.config/letsencrypt/cli.ini"
        section: null
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      become: true
      become_user: root
      loop:
        - option: "server"
          value: "https://pebble:14000/dir"
        - option: "no-verify-ssl"
          value: "1"
